services:
  web:
    build: .
    working_dir: /big6
    volumes:
      - .:/big6
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: